version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=mystockdb
      - POSTGRES_USER=mystock
      - POSTGRES_PASSWORD=c10neC0ding1nZozz
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=mystockdb
      - POSTGRES_USER=mystock
      - POSTGRES_PASSWORD=c10neC0ding1nZozz
    depends_on:
      - db

volumes:
  pg_data:
