# Generated by Django 3.2.14 on 2022-11-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []  # type: ignore

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(help_text="이름", max_length=32)),
                ("phone", models.CharField(help_text="전화번호", max_length=32)),
                ("email", models.CharField(help_text="이메일", max_length=128)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
