# Generated by Django 3.2.14 on 2022-09-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="code",
            field=models.CharField(help_text="주식코드", max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="kr_name",
            field=models.CharField(help_text="국문 주식명", max_length=64),
        ),
    ]
