# Generated by Django 3.2.14 on 2022-12-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0003_auto_20220909_2329"),
    ]

    operations = [
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kr_name",
                    models.CharField(help_text="국문 테마명", max_length=64, unique=True),
                ),
                (
                    "kr_explanation",
                    models.TextField(blank=True, default="", help_text="국문 테마 설명"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
